#############################################################################
# Makefile for building: QFc
# Generated by qmake (3.1) (Qt 5.15.8)
# Project:  QFc.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile QFc.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -O3 -march=native -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -fopt-info-optimized-vec-loop-omp -O2 -O3 -march=native -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -fopt-info-optimized-vec-loop-omp -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O3 -march=native -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -fopt-info-optimized-vec-loop-omp -O2 -O3 -march=native -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -fopt-info-optimized-vec-loop-omp -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = QFc1.0.0
DISTDIR = /home/sheridan/Desktop/ERGASIES/QFc/.tmp/QFc1.0.0
LINK          = g++
LFLAGS        = -O3 -Wl,-O1
LIBS          = $(SUBLIBS) -lm -fopenmp /usr/lib/x86_64-linux-gnu/libQt5Core.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = KmeansPP.cpp \
		QfcRandom.cc \
		Rbf.cc \
		collection.cc \
		converter.cc \
		cprogram.cc \
		demethod.cpp \
		doubleinterval.cpp \
		doublestack.cc \
		fparser.cc \
		fpoptimizer.cc \
		gensolver.cc \
		getoptions.cpp \
		grs.cc \
		integergenetic.cpp \
		interval.cpp \
		kmeans.cc \
		knn.cc \
		lbfgs.cpp \
		main.cpp \
		mapper.cc \
		matrix_functions.cc \
		model.cc \
		neural.cc \
		neuralparser.cc \
		neuralprogram.cc \
		nnc.cpp \
		nncneuralprogram.cc \
		nnprogram.cc \
		osamarbf.cpp \
		population.cc \
		problem.cc \
		program.cc \
		psoge.cpp \
		qfcmethod.cpp \
		rbf_model.cc \
		rbfsolver.cc \
		rlsprogram.cc \
		rule.cc \
		sigprogram.cc \
		symbol.cc \
		tolmin.cc 
OBJECTS       = KmeansPP.o \
		QfcRandom.o \
		Rbf.o \
		collection.o \
		converter.o \
		cprogram.o \
		demethod.o \
		doubleinterval.o \
		doublestack.o \
		fparser.o \
		fpoptimizer.o \
		gensolver.o \
		getoptions.o \
		grs.o \
		integergenetic.o \
		interval.o \
		kmeans.o \
		knn.o \
		lbfgs.o \
		main.o \
		mapper.o \
		matrix_functions.o \
		model.o \
		neural.o \
		neuralparser.o \
		neuralprogram.o \
		nnc.o \
		nncneuralprogram.o \
		nnprogram.o \
		osamarbf.o \
		population.o \
		problem.o \
		program.o \
		psoge.o \
		qfcmethod.o \
		rbf_model.o \
		rbfsolver.o \
		rlsprogram.o \
		rule.o \
		sigprogram.o \
		symbol.o \
		tolmin.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		QFc.pro KmeansPP.h \
		QfcRandom.h \
		Rbf.h \
		Util.h \
		collection.h \
		converter.h \
		cprogram.h \
		demethod.h \
		doubleinterval.h \
		doublestack.h \
		f2c.h \
		fparser.hh \
		fpconfig.hh \
		fptypes.hh \
		gensolver.h \
		getoptions.h \
		grs.h \
		integergenetic.h \
		interval.h \
		kmeans.h \
		knn.h \
		lbfgs.h \
		mapper.h \
		matrix_functions.h \
		model.h \
		neural.h \
		neuralparser.h \
		neuralprogram.h \
		nnc.h \
		nncneuralprogram.h \
		nnprogram.h \
		osamarbf.h \
		population.h \
		problem.h \
		program.h \
		psoge.h \
		qfcmethod.h \
		rbf_model.h \
		rbfsolver.h \
		rlsprogram.h \
		rule.h \
		sigprogram.h \
		symbol.h KmeansPP.cpp \
		QfcRandom.cc \
		Rbf.cc \
		collection.cc \
		converter.cc \
		cprogram.cc \
		demethod.cpp \
		doubleinterval.cpp \
		doublestack.cc \
		fparser.cc \
		fpoptimizer.cc \
		gensolver.cc \
		getoptions.cpp \
		grs.cc \
		integergenetic.cpp \
		interval.cpp \
		kmeans.cc \
		knn.cc \
		lbfgs.cpp \
		main.cpp \
		mapper.cc \
		matrix_functions.cc \
		model.cc \
		neural.cc \
		neuralparser.cc \
		neuralprogram.cc \
		nnc.cpp \
		nncneuralprogram.cc \
		nnprogram.cc \
		osamarbf.cpp \
		population.cc \
		problem.cc \
		program.cc \
		psoge.cpp \
		qfcmethod.cpp \
		rbf_model.cc \
		rbfsolver.cc \
		rlsprogram.cc \
		rule.cc \
		sigprogram.cc \
		symbol.cc \
		tolmin.cc
QMAKE_TARGET  = QFc
DESTDIR       = 
TARGET        = QFc


first: all
####### Build rules

QFc:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QFc.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		QFc.pro
	$(QMAKE) -o Makefile QFc.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
QFc.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile QFc.pro

qmake_all: FORCE


all: Makefile QFc

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents KmeansPP.h QfcRandom.h Rbf.h Util.h collection.h converter.h cprogram.h demethod.h doubleinterval.h doublestack.h f2c.h fparser.hh fpconfig.hh fptypes.hh gensolver.h getoptions.h grs.h integergenetic.h interval.h kmeans.h knn.h lbfgs.h mapper.h matrix_functions.h model.h neural.h neuralparser.h neuralprogram.h nnc.h nncneuralprogram.h nnprogram.h osamarbf.h population.h problem.h program.h psoge.h qfcmethod.h rbf_model.h rbfsolver.h rlsprogram.h rule.h sigprogram.h symbol.h $(DISTDIR)/
	$(COPY_FILE) --parents KmeansPP.cpp QfcRandom.cc Rbf.cc collection.cc converter.cc cprogram.cc demethod.cpp doubleinterval.cpp doublestack.cc fparser.cc fpoptimizer.cc gensolver.cc getoptions.cpp grs.cc integergenetic.cpp interval.cpp kmeans.cc knn.cc lbfgs.cpp main.cpp mapper.cc matrix_functions.cc model.cc neural.cc neuralparser.cc neuralprogram.cc nnc.cpp nncneuralprogram.cc nnprogram.cc osamarbf.cpp population.cc problem.cc program.cc psoge.cpp qfcmethod.cpp rbf_model.cc rbfsolver.cc rlsprogram.cc rule.cc sigprogram.cc symbol.cc tolmin.cc $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O3 -march=native -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -fopt-info-optimized-vec-loop-omp -O2 -O3 -march=native -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -fopt-info-optimized-vec-loop-omp -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

KmeansPP.o: KmeansPP.cpp KmeansPP.h \
		model.h \
		problem.h \
		mapper.h \
		fparser.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o KmeansPP.o KmeansPP.cpp

QfcRandom.o: QfcRandom.cc QfcRandom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QfcRandom.o QfcRandom.cc

Rbf.o: Rbf.cc Rbf.h \
		matrix_functions.h \
		kmeans.h \
		model.h \
		problem.h \
		mapper.h \
		fparser.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Rbf.o Rbf.cc

collection.o: collection.cc collection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o collection.o collection.cc

converter.o: converter.cc converter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o converter.o converter.cc

cprogram.o: cprogram.cc cprogram.h \
		symbol.h \
		rule.h \
		doublestack.h \
		fparser.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cprogram.o cprogram.cc

demethod.o: demethod.cpp demethod.h \
		problem.h \
		neural.h \
		model.h \
		mapper.h \
		fparser.hh \
		kmeans.h \
		lbfgs.h \
		f2c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o demethod.o demethod.cpp

doubleinterval.o: doubleinterval.cpp doubleinterval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doubleinterval.o doubleinterval.cpp

doublestack.o: doublestack.cc doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doublestack.o doublestack.cc

fparser.o: fparser.cc fparser.hh \
		fpconfig.hh \
		fptypes.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fparser.o fparser.cc

fpoptimizer.o: fpoptimizer.cc fpconfig.hh \
		fparser.hh \
		fptypes.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fpoptimizer.o fpoptimizer.cc

gensolver.o: gensolver.cc gensolver.h \
		problem.h \
		neural.h \
		model.h \
		mapper.h \
		fparser.hh \
		getoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gensolver.o gensolver.cc

getoptions.o: getoptions.cpp getoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o getoptions.o getoptions.cpp

grs.o: grs.cc grs.h \
		population.h \
		program.h \
		symbol.h \
		rule.h \
		doublestack.h \
		qfcmethod.h \
		interval.h \
		rlsprogram.h \
		problem.h \
		fparser.hh \
		collection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grs.o grs.cc

integergenetic.o: integergenetic.cpp integergenetic.h \
		qfcmethod.h \
		program.h \
		symbol.h \
		rule.h \
		doublestack.h \
		interval.h \
		nnprogram.h \
		cprogram.h \
		fparser.hh \
		model.h \
		problem.h \
		mapper.h \
		neural.h \
		rbf_model.h \
		Rbf.h \
		matrix_functions.h \
		kmeans.h \
		knn.h \
		doubleinterval.h \
		population.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integergenetic.o integergenetic.cpp

interval.o: interval.cpp interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interval.o interval.cpp

kmeans.o: kmeans.cc kmeans.h \
		model.h \
		problem.h \
		mapper.h \
		fparser.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kmeans.o kmeans.cc

knn.o: knn.cc knn.h \
		model.h \
		problem.h \
		mapper.h \
		fparser.hh \
		gensolver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knn.o knn.cc

lbfgs.o: lbfgs.cpp lbfgs.h \
		problem.h \
		f2c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lbfgs.o lbfgs.cpp

main.o: main.cpp getoptions.h \
		population.h \
		program.h \
		symbol.h \
		rule.h \
		doublestack.h \
		qfcmethod.h \
		interval.h \
		nnprogram.h \
		cprogram.h \
		fparser.hh \
		model.h \
		problem.h \
		mapper.h \
		neural.h \
		rbf_model.h \
		Rbf.h \
		matrix_functions.h \
		kmeans.h \
		knn.h \
		osamarbf.h \
		Util.h \
		KmeansPP.h \
		psoge.h \
		nnc.h \
		nncneuralprogram.h \
		neuralprogram.h \
		sigprogram.h \
		neuralparser.h \
		QfcRandom.h \
		integergenetic.h \
		doubleinterval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mapper.o: mapper.cc mapper.h \
		fparser.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mapper.o mapper.cc

matrix_functions.o: matrix_functions.cc matrix_functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o matrix_functions.o matrix_functions.cc

model.o: model.cc model.h \
		problem.h \
		mapper.h \
		fparser.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model.o model.cc

neural.o: neural.cc neural.h \
		model.h \
		problem.h \
		mapper.h \
		fparser.hh \
		gensolver.h \
		grs.h \
		population.h \
		program.h \
		symbol.h \
		rule.h \
		doublestack.h \
		qfcmethod.h \
		interval.h \
		rlsprogram.h \
		collection.h \
		demethod.h \
		lbfgs.h \
		f2c.h \
		getoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neural.o neural.cc

neuralparser.o: neuralparser.cc neuralparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neuralparser.o neuralparser.cc

neuralprogram.o: neuralprogram.cc neuralprogram.h \
		program.h \
		symbol.h \
		rule.h \
		doublestack.h \
		sigprogram.h \
		cprogram.h \
		fparser.hh \
		neuralparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neuralprogram.o neuralprogram.cc

nnc.o: nnc.cpp nnc.h \
		model.h \
		problem.h \
		mapper.h \
		fparser.hh \
		nncneuralprogram.h \
		neuralprogram.h \
		program.h \
		symbol.h \
		rule.h \
		doublestack.h \
		sigprogram.h \
		cprogram.h \
		neuralparser.h \
		population.h \
		qfcmethod.h \
		interval.h \
		getoptions.h \
		converter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nnc.o nnc.cpp

nncneuralprogram.o: nncneuralprogram.cc nncneuralprogram.h \
		neuralprogram.h \
		program.h \
		symbol.h \
		rule.h \
		doublestack.h \
		sigprogram.h \
		cprogram.h \
		fparser.hh \
		neuralparser.h \
		QfcRandom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nncneuralprogram.o nncneuralprogram.cc

nnprogram.o: nnprogram.cc nnprogram.h \
		program.h \
		symbol.h \
		rule.h \
		doublestack.h \
		cprogram.h \
		fparser.hh \
		model.h \
		problem.h \
		mapper.h \
		neural.h \
		rbf_model.h \
		Rbf.h \
		matrix_functions.h \
		kmeans.h \
		knn.h \
		QfcRandom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nnprogram.o nnprogram.cc

osamarbf.o: osamarbf.cpp osamarbf.h \
		model.h \
		problem.h \
		mapper.h \
		fparser.hh \
		Util.h \
		KmeansPP.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o osamarbf.o osamarbf.cpp

population.o: population.cc population.h \
		program.h \
		symbol.h \
		rule.h \
		doublestack.h \
		qfcmethod.h \
		interval.h \
		problem.h \
		nnprogram.h \
		cprogram.h \
		fparser.hh \
		model.h \
		mapper.h \
		neural.h \
		rbf_model.h \
		Rbf.h \
		matrix_functions.h \
		kmeans.h \
		knn.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o population.o population.cc

problem.o: problem.cc problem.h \
		QfcRandom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o problem.o problem.cc

program.o: program.cc program.h \
		symbol.h \
		rule.h \
		doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o program.o program.cc

psoge.o: psoge.cpp psoge.h \
		program.h \
		symbol.h \
		rule.h \
		doublestack.h \
		qfcmethod.h \
		interval.h \
		nnprogram.h \
		cprogram.h \
		fparser.hh \
		model.h \
		problem.h \
		mapper.h \
		neural.h \
		rbf_model.h \
		Rbf.h \
		matrix_functions.h \
		kmeans.h \
		knn.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o psoge.o psoge.cpp

qfcmethod.o: qfcmethod.cpp qfcmethod.h \
		program.h \
		symbol.h \
		rule.h \
		doublestack.h \
		interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qfcmethod.o qfcmethod.cpp

rbf_model.o: rbf_model.cc rbf_model.h \
		model.h \
		problem.h \
		mapper.h \
		fparser.hh \
		Rbf.h \
		matrix_functions.h \
		kmeans.h \
		rbfsolver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rbf_model.o rbf_model.cc

rbfsolver.o: rbfsolver.cc rbfsolver.h \
		problem.h \
		rbf_model.h \
		model.h \
		mapper.h \
		fparser.hh \
		Rbf.h \
		matrix_functions.h \
		kmeans.h \
		QfcRandom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rbfsolver.o rbfsolver.cc

rlsprogram.o: rlsprogram.cc rlsprogram.h \
		problem.h \
		population.h \
		program.h \
		symbol.h \
		rule.h \
		doublestack.h \
		qfcmethod.h \
		interval.h \
		fparser.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rlsprogram.o rlsprogram.cc

rule.o: rule.cc rule.h \
		symbol.h \
		doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rule.o rule.cc

sigprogram.o: sigprogram.cc sigprogram.h \
		cprogram.h \
		symbol.h \
		rule.h \
		doublestack.h \
		fparser.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sigprogram.o sigprogram.cc

symbol.o: symbol.cc symbol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o symbol.o symbol.cc

tolmin.o: tolmin.cc problem.h \
		neural.h \
		model.h \
		mapper.h \
		fparser.hh \
		f2c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tolmin.o tolmin.cc

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/QFc/bin || mkdir -p $(INSTALL_ROOT)/opt/QFc/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/QFc/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/QFc/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/QFc/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/QFc/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

